apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emctest
spec:
  template:
    metadata:
      labels:
        app: {{ template "emc.fullname" . }}-emctest
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: emctest
        image: dptest.azurecr.io/emctest
      imagePullSecrets:
      - name: acr-auth
      ports:
      - name: {{.Values.containerPort}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.servicePort }}
{{- if .Values.ingress.tls }}
  tls:
  - secretName: {{ .Values.ingress.hostname | quote }}
    hosts:
      - {{ .Values.ingress.hostname | quote }}
{{- end -}}
{{- end }}