apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emctest
spec:
  template:
    metadata:
      labels:
        app: {{ template "emc.fullname" . }}-emctest
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: emctest
        image: dptest.azurecr.io/emctest
      imagePullSecrets:
      - name: acr-auth