name: Trigger auto deployment for dpacatest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dpacatest-AutoDeployTrigger-82f2343e-1ac3-4fe8-82d6-436a760ba68d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: dptest.azurecr.io
          username: ${{ secrets.DPACATEST_REGISTRY_USERNAME }}
          password: ${{ secrets.DPACATEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dptest.azurecr.io/dpacatest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DPACATEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n dpacatest -g dpacatest --server dptest.azurecr.io --username  ${{ secrets.DPACATEST_REGISTRY_USERNAME }} --password ${{ secrets.DPACATEST_REGISTRY_PASSWORD }}
            az containerapp update -n dpacatest -g dpacatest --image dptest.azurecr.io/dpacatest:${{ github.sha }}
